name: "An alternate way to syndicate"
on:
  push:
    branches:
    - master
    - develop
    paths:
    - 'pages/**/*.mdx?'

jobs:
  syndicate:
    runs-on: ubuntu-latest
    name: Syndicate posts
    env:
      # This is provided to all actions by Github, and needed to access the posts
      # in your repository.
      # @see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Tell me the path (relative to the project root) where your posts live, so I can find them.
      # Defaults to 'posts'.
      SYNDICATE_POST_DIR: 'pages/posts'
    steps:
    - name: Push to DEV.to
      id: DEV
      uses: dabrady/syndicate@develop
      with:
        silos: DEV
      env:
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}

    - name: Report DEV.to results
      run: 'echo "${{ toJSON(steps.DEV.outputs) }}"'

    - name: Push to Medium and Planet Mars
      uses: dabrady/syndicate@develop
      id: Medium
      with:
        silos: |
          Medium
          Planet_Mars
      env:
        MEDIUM_API_KEY: "fake"
        PLANET_MARS_API_KEY: "fake"

    - name: Report results
      id: report
      run:
        'echo "The results are in! ${{ toJSON(env.SYNDICATE_POSTS) }}"'

    - name: Update posts with syndicate IDs
      uses: dabrady/syndicate@develop
      with:
        mark_as_syndicated: true
