on: [push]

jobs:
  syndicate:
    runs-on: ubuntu-latest
    name: Example syndicate workflow
    steps:
    - name: Syndicate published content changes
      id: syndicate
      uses: dabrady/syndicate@master
      with:
        silos:
          - DEV
          - Medium
          - Mars
    - name: Get the output time
      run: echo "The time was ${{ steps.syndicate.outputs.time }}"
