on:
  push:
    branches:
    - master
    - develop
    paths:
    - 'pages/**/*.mdx?'

jobs:
  syndicate:
    runs-on: ubuntu-latest
    name: Example syndicate workflow
    steps:
    - name: Syndicate to silos
      id: syndicate
      uses: dabrady/syndicate@develop
      with:
        # Using a YAML multiline string as a workaround for a list argument.
        # @see https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/td-p/33776
        # Names are snake_case, case-insensitive.
        silos: |
          DEV
          Medium
          Planet_Mars
      env:
        # This is provided to all actions by Github, and needed to access the posts
        # in your repository.
        # @see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Tell me the path (relative to the project root) where your posts live, so I can find them.
        # Defaults to 'posts'.
        SYNDICATE_POST_DIR: 'pages/posts'
        # Set necessary API keys as secrets of your repo and specify them here in this format:
        #
        #   <SCREAMING_SNAKE_CASE_SILO_NAME>_API_KEY
        #
        # e.g.
        #
        #   MEDIUM_API_KEY
        #
        # so that the action can find them easily when needed.
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
    - name: Get the output time
      run: echo "The time was ${{ steps.syndicate.outputs.time }}"
